### ISSUE TITLE
table ignore flag

### ISSUE THREAD

**Issue by atmediauk** [schickling/laravel-backup#11]
Would it be possible to have a table ignore flag.

For example php artisan db:backup --ignore="table_x"

The reason I ask is because I have some tables that do not change but are pretty big. One example would be an address lookup table. The size of these tables goes into the gigabytes so doing a backup of them every single time wastes a lot of time, server resources and space. I would rather create a backup with them lets say once, and then in the future ignore them.

What would also be cool is if to the end of the filename of the backup it can just append something like _ignoring_table_x as an indicator. That way when doing a restore you can see which backups may be ignoring tables at a glance.

I guess this could also lead onto having a --only flag which lets you say which tables you only want backing up.

Let me know what you think and thanks a lot. The package has been great so far.

**Comment by schickling** [comment]
Hi @atmediauk,

Thanks for this nice idea. I'm kinda busy these days so currently I don't have the time to do this on my own but please feel free to hand in some pull requests!

**Comment by atmediauk** [comment]
Sure, I'l have a go. If i'm successful i'll request a PR
