### ISSUE TITLE
db:backup is not defined

### ISSUE THREAD

**Issue by christoferd** [schickling/laravel-backup#12]
Hi Johannes,

I'm getting this error: db:backup is not defined

I've tried adding this `"schickling/backup": "dev-master"`
to "require" and "require-dev" in composer.json
and still get same issue.

I have run `composer self-update` and `composer update`, still not recognizing the command.

This is the first package this has happened with, and I cannot work out why. Would appreciate your help.

Thanks, 
Chris.

**Comment by schickling** [comment]
Hi @christoferd 

Are you sure you've done the second installation step?

> Add `Schickling\Backup\BackupServiceProvider` to your config/app.php

**Comment by christoferd** [comment]
Hi @schickling 

How embarrassing, I forgot to do that step. Oh well, hope this helps other people.

Thanks for help : )

**Comment by schickling** [comment]
No problem :)
