### ISSUE TITLE
Backup Restored Successfully, but nothing changed

### ISSUE THREAD

**Issue by christoferd** [schickling/laravel-backup#13]
Hi Johannes ,

I see message "20131023134411.sql was successfully restored." 
**Issue:** nothing changed in DB.

What I did
1. On my DEV machine > `php artisan db:backup` 
... then git commit, then push all files. The file is not ignored and it is uploaded.
2. On live server `git pull`, including the backup file in /storage/dump/ folder.
... then I run > `php artisan db:restore`, it says "20131023134411.sql was successfully restored." however the database has not changed at all :-/ 

_very strange I think_

Any ideas?

**Comment by schickling** [comment]
Are you sure the databases on your dev and prod env are called the same?

**Comment by christoferd** [comment]
Yes, DB same name, User same, Password same. My application works. php artisan works. 
Early stages of development. 
I am not using 'production' yet, just 'local' and 'staging' at moment. Note that I only have _one_ app.php file for now, so there is no issues there.

Found another issue; 

```
$ php artisan db:restore 20131025095502.sql
20131025095502.sql was successfully restored.
```

However the file did not exist. Due to git pull failing and didn't notice.
Then however, when I did successfully pull the database dump to staging server. 
I get the _exact same message._

Obviously the script is not checking if any file was actually loaded.
And, it's obvious that there is no check to see if any sql statements have been executed, etc.

Just want to say thank you, your package is helping me : )
Hack solution: at the moment I backup on dev machine, then use phpmyadmin Import to run the file.

**Comment by schickling** [comment]
Thanks I'll have a look on that!

**Comment by christoferd** [comment]
@schickling 
1. Just thought let you know, I'm still using default "root" with pass "" at moment. Would that cause issue?
2. Does your plugin have Linux only commands perhaps?
   My PC and staging server are both Windows PC's running WAMP.

**Comment by schickling** [comment]
@christoferd I've only tested it on unix systems.

**Comment by christoferd** [comment]
Just wondering, are there any specific linux shell commands being used, or is it all Laravel class methods based?
This may be the cause of my issue.

**Comment by schickling** [comment]
For mysql the package relies on `mysqldump`

But you also got the option the specify the binary path in the configuration.

**Comment by christoferd** [comment]
Ok thanks for that.
Yes, "mysqldump" is working from command line.
The bin folder is in my PATH.
I'll come back to this another day, for now just using the backup feature
and manually importing. It's good enough ;)
Thank you
- Chris

**Comment by schickling** [comment]
I'm not sure when php runs a command, whether it uses your bash (...) PATH.
Have you tried the custom path configuration option of this package?
