### ISSUE TITLE
Support for mysql port

### ISSUE THREAD

**Issue by lostincode** [schickling/laravel-backup#16]
Is there any way to specify the mysql port? e.g. -P 3307 in the mysqldump command

**Comment by schickling** [comment]
If you refer to that: http://dev.mysql.com/doc/refman/5.1/en/mysqldump.html#option_mysqldump_port

I haven't implemented this option yet, but feel free to create a pull request for that. Please also provide a default value if you do so :+1:

**Comment by lostincode** [comment]
Sure, ill post something in a few minutes for you to give feedback.
