### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by dragonfire1119** [schickling/laravel-backup#18]
I get a error when using it

```
Database backup failed. Warning: Using a password on the command line interface can be insecure.
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect
```

It creates the .sql but its empty. Also how would I use this script in laravel instead of the command line.

**Comment by schickling** [comment]
Please check this: http://stackoverflow.com/questions/16325607/cant-connect-to-local-mysql-server-through-socket-tmp-mysql-sock

This has nothing to do with the package on its own.

**Comment by dragonfire1119** [comment]
Ok I got it to work I needed to use 127.0.0.1 instead of localhost. Thanks for the support.
