### ISSUE TITLE
laravel-backup as package dependency

### ISSUE THREAD

**Issue by subdesign** [schickling/laravel-backup#24]
I try to add your package as dependency, but can't install it. I add 
"schickling/backup":"dev-master"
to my package composer.json, push to github, and install my package via composer, installs all the dependent packages (for example dropbox-php), but your package isn't installed. Any idea why?

**Comment by schickling** [comment]
I'm pretty sure that's not related to this package itself. Sorry, but I haven't heard about problems like this before...

**Comment by subdesign** [comment]
Ok, I'll figure out what's the situation, and go back to report

**Comment by subdesign** [comment]
So forgot to set the main composer.json to dev in minimum-stability, now works, thanks
