### ISSUE TITLE
Request: Restore from S3

### ISSUE THREAD

**Issue by jorisnoo** [schickling/laravel-backup#26]
Hi schickling!

Thanks for your great work. Would restoring dump files from the s3 server be possible and by any chance on the roadmap?

Cheers,
joris

**Comment by schickling** [comment]
Hey @jorisnoo,

I guess that would be a great feature but unfortunately I don't have the time to implement it on my own. But I'd love to merge a PR that implements this feature.

Feel free to contribute! :+1:

**Comment by jorisnoo** [comment]
Hey @schickling 

Thanks, I'll consider it! :)
