### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by FR6** [schickling/laravel-backup#28]
Just a suggestion: 
You should not put the settings in the `app/config/database.php` but create a new file based on your package in: `app/config/packages/schickling/laravel-backup/backup.php`.

**Comment by 7LayersDesign** [comment]
I agree. I would prefer not to mix packages in with my database config.

**Comment by schickling** [comment]
I hope everything works for you guys with the new version :)

**Comment by 7LayersDesign** [comment]
Wow! Very quick response.
