### ISSUE TITLE
Error: Using $this when not in object context

### ISSUE THREAD

**Issue by BenCavens** [schickling/laravel-backup#3]
I try to run the backup service via artisan but fatal php error (using $this when not in object context) on the register method prevents scriptrun. 
I hope this console screenshot is sufficient. 

![schickling](https://f.cloud.github.com/assets/497668/732674/f1fbc016-e288-11e2-9d1a-31a604298fca.jpg)

Ben

**Comment by schickling** [comment]
Thanks @BenCavens for your report! Should be fixed by now. Can you confirm that?

**Comment by BenCavens** [comment]
yep. thanks
